### ISSUE TITLE
Filter Pruning Error

### ISSUE THREAD

**Issue by 408550969** [slothkong/DNN-Pruning#4]
Hi
When I started pruning resnet,appeared an error:
------------------------------
	 Filter Pruning 
------------------------------
operating: conv = conv1 , convnext = res2a_branch1, bn = bn_conv1, dc = 32
Traceback (most recent call last):
  File "filter_pruning_demo.py", line 748, in <module>
    prune_me = pruneLayer(prune_me, conv, convnext, bn, affine, dc)
  File "filter_pruning_demo.py", line 139, in pruneLayer
    net.WPQ[(conv_P,1)] =  net.param_b_data(conv)
  File "/home/cll/DNN-Pruning-master/lib/net.py", line 221, in param_b_data
    return self.param_b(name).data
  File "/home/cll/DNN-Pruning-master/lib/net.py", line 215, in param_b
    return self.param(name)[1]
IndexError: Index out of range

**Comment by slothkong** [comment]
> File "/home/cll/DNN-Pruning-master/lib/net.py", line 215, in param_b
return self.param(name)[1]

I think this might be happening because this particular version of `.caffemodel` you are using does not implement biases. Could you tell me what specific model are you using?

**Comment by 408550969** [comment]
Yes, I also found it is the bias problem. 
I use the Resnet model,which bias_term is false in every conv.

**Comment by slothkong** [comment]
If you want to use a Resnet with biases ,a work around this problem is to to evaulate if the mode has bias, catch the exception in case it does not have, and then activate a flag the will indicate the code 
 that no operation is required on bias elements.  Unfortunately I think that is the only solution I can think of,  and is not elegant at all.

**Comment by 408550969** [comment]
Thanks!
